gestao-ferias/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::resource('/lista','FuncionarioController');

gestao-ferias/app/Models/Funcionario.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Funcionario extends Model
{
    use HasFactory;
    protected  $fillable =['nome','apelido','endereco','area'];
}

gestao-ferias/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

gestao-ferias/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

gestao-ferias/app/Http/Controllers/FuncionarioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Funcionario;


class FuncionarioController extends Controller
{
    private $funcionario; 
    
    public function __construct(Funcionario $funcionario){
       
     $this->funcionario=$funcionario;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $func= $this->funcionario->all();

        return view('ListaFuncionarios', compact('func'));   

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('adicionar');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        return 'Cadastrando...';
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function teste(){
        return 'testando';
        // $func= $this->funcionario->create([
        //     'nome'      =>'Joao',
        //     'apelido'   => 'Aniquilas',
        //     'endereco'  =>'bairro B13',
        //     'area'      =>'gestor de DB'
        // ]);

        // $insert=$func->save();

        // if($insert)
        // return 'Inserido com sucesso';
        //     else
        //     return 'Falaha na insercao';
    }
}

gestao-ferias/app/Http/Controllers/FuncionarioController1.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;


class FuncionarioController extends Controller
{
   

    public function index(){

        $func= $this->funcionario->all();

        return view('ListaFuncionarios', compact('func'));
    }
}

gestao-ferias/resources/views/ListaFuncionarios.blade.php
@extends('layout')

@section('content')
<div class="container">


<h1 class=""> Lista dos funcionarios!</h1>

<a href="{{route('lista.create')}}" class="btn btn-primary"> Adicionar</a>
<br>
<br>
<table class="table hover">
<tr>
<th>ID</th>
<th>Nome</th>
<th>Apelido </th>
<th> Endereco</th>
<th>Area de Job </th>
<th>Accao</th>
</tr>
@foreach($func as $funcionari)
<tr>
<td>{{$funcionari->id }}</td>
<td>{{$funcionari->nome }}</td>
<td>{{$funcionari->apelido}}</td>
<td>{{$funcionari->endereco }}</td>
<td>{{$funcionari->area}}</td>
<td><a href="" > <span class="bg-dark text-light"> Editar</span> </a></td>
<td><a href="" > <span class="bg-danger text-light"> Remover</span> </a></td>
</tr>
@endforeach


</table>


</div>


@endsection

gestao-ferias/resources/views/adicionar.blade.php
@extends('layout')
@section('content')

<div class="container">
<br>
<br>
<br>

<div class=" justify-content-center">


<form class="bg-light" method="post" action="{{ url('lista/store')}}" >
<input type="hidden" name="_token" value="{{csrf_token()}}">

<div class="form-group">
<span> Nome: </span>
<input type="text" class="form-control" name="nome">
</div>
<div class="form-group">
<span> Apelido: </span>
<input type="text" class="form-control" name="apelido">
</div>
<div class="form-group">
<span> Endereco: </span>
<input type="text" class="form-control" name="endereco">
</div>
<div class="form-group">
<span> Area do job </span>
{{-- <select name="area" id="">
@foreach($func as $funcionario)
<option value="{{$funcionario->area}}">{{$funcionario->area}}</option>
@endforeach --}}
</select>
</div>
<button class="btn btn-primary">Adicionar </button> 
<div class="form-group">
</div>

</form>


</div>
</div>



@endsection

gestao-ferias/resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{{ url('assets/css/bootstrap-custom.min.css')}}">
    <title>Funcionarios</title>
</head>
<body>

@yield('content')
    
</body>
</html>